import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, realpath, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadProjectOnlyInstincts } from "../lib/instincts.js";
import { detectProject } from "../lib/project.js";
import { resolveInstinctOutputDir } from "../lib/skill-create.js";
import { ensureStorage, getStorageLayout } from "../lib/storage.js";
import type { InstinctDraft, ProjectInfo } from "../lib/types.js";

export interface ScopeValidationResult {
	gitProject: {
		rootDetected: boolean;
		idIsGlobal: boolean;
	};
	nonGitFallback: {
		idIsGlobal: boolean;
	};
	override: {
		rootMatchesOverride: boolean;
	};
	globalFallbackInstincts: {
		count: number;
		allGlobal: boolean;
	};
	instinctRouting: {
		globalDirMatches: boolean;
		projectDirMatches: boolean;
	};
}

function git(args: string[], cwd: string): string {
	const result = spawnSync("git", args, {
		cwd,
		encoding: "utf-8",
	});
	if (result.status !== 0) {
		throw new Error(`Command failed: git ${args.join(" ")}\n${result.stderr}`);
	}
	return result.stdout.trim();
}

function createDraft(scope: "project" | "global"): InstinctDraft {
	return {
		id: `${scope}-scope-validation`,
		title: `${scope} scope validation`,
		trigger: "when validating scope behavior",
		confidence: 0.8,
		domain: "workflow",
		scope,
		action: "Validate the target storage directory.",
		evidence: ["Generated by scope-validation.mts"],
	};
}

function assertValidation(condition: boolean, message: string): void {
	if (!condition) {
		throw new Error(message);
	}
}

export async function runScopeValidation(): Promise<ScopeValidationResult> {
	const tempRoot = await realpath(await mkdtemp(join(tmpdir(), "pi-clv2-scope-")));
	const previousAgentDir = process.env.PI_CODING_AGENT_DIR;
	const previousProjectDir = process.env.PI_PROJECT_DIR;
	const previousClaudeProjectDir = process.env.CLAUDE_PROJECT_DIR;

	try {
		const agentDir = join(tempRoot, "agent");
		process.env.PI_CODING_AGENT_DIR = agentDir;
		await mkdir(agentDir, { recursive: true });

		const repoRoot = join(tempRoot, "repo");
		const nestedDir = join(repoRoot, "src", "nested");
		const nonGitDir = join(tempRoot, "plain");
		const overrideCwd = join(tempRoot, "override-cwd");
		await mkdir(nestedDir, { recursive: true });
		await mkdir(nonGitDir, { recursive: true });
		await mkdir(overrideCwd, { recursive: true });

		git(["init", "--initial-branch=main"], repoRoot);
		git(["config", "--local", "user.email", "test@test.com"], repoRoot);
		git(["config", "--local", "user.name", "Test"], repoRoot);
		await writeFile(join(repoRoot, "README.md"), "# Scope Validation\n", "utf-8");
		git(["add", "README.md"], repoRoot);
		git(["commit", "-m", "feat: init"], repoRoot);

		delete process.env.PI_PROJECT_DIR;
		delete process.env.CLAUDE_PROJECT_DIR;
		const detectedGitProject = await detectProject(nestedDir);
		const nonGitProject = await detectProject(nonGitDir);

		process.env.PI_PROJECT_DIR = repoRoot;
		const overrideProject = await detectProject(overrideCwd);
		delete process.env.PI_PROJECT_DIR;

		const globalProject: ProjectInfo = {
			id: "global",
			name: "global",
			root: nonGitDir,
		};
		const globalLayout = getStorageLayout(globalProject);
		await ensureStorage(globalProject, globalLayout);
		await writeFile(
			join(globalLayout.globalPersonalDir, "global-personal.md"),
			[
				"---",
				"id: global-personal",
				"title: Global Personal",
				"trigger: when validating global fallback",
				"confidence: 0.8",
				"domain: workflow",
				"scope: global",
				"---",
				"",
				"# Global Personal",
				"",
				"## Action",
				"Use the global personal instinct.",
			].join("\n"),
			"utf-8",
		);
		await writeFile(
			join(globalLayout.globalInheritedDir, "global-inherited.md"),
			[
				"---",
				"id: global-inherited",
				"title: Global Inherited",
				"trigger: when validating imported global fallback",
				"confidence: 0.7",
				"domain: workflow",
				"scope: global",
				"source: inherited",
				"---",
				"",
				"# Global Inherited",
				"",
				"## Action",
				"Use the imported global instinct.",
			].join("\n"),
			"utf-8",
		);
		const globalInstincts = await loadProjectOnlyInstincts(globalLayout);

		const routedProject: ProjectInfo = {
			id: detectedGitProject.id,
			name: detectedGitProject.name,
			root: repoRoot,
			remote: detectedGitProject.remote,
		};
		const routedLayout = getStorageLayout(routedProject);
		await ensureStorage(routedProject, routedLayout);

		const result: ScopeValidationResult = {
			gitProject: {
				rootDetected: detectedGitProject.root === repoRoot,
				idIsGlobal: detectedGitProject.id === "global",
			},
			nonGitFallback: {
				idIsGlobal: nonGitProject.id === "global",
			},
			override: {
				rootMatchesOverride: overrideProject.root === repoRoot,
			},
			globalFallbackInstincts: {
				count: globalInstincts.length,
				allGlobal: globalInstincts.every((instinct) => instinct.scopeLabel === "global"),
			},
			instinctRouting: {
				globalDirMatches:
					resolveInstinctOutputDir(routedLayout, routedProject, createDraft("global")) ===
					routedLayout.globalPersonalDir,
				projectDirMatches:
					resolveInstinctOutputDir(routedLayout, routedProject, createDraft("project")) ===
					routedLayout.projectPersonalDir,
			},
		};

		assertValidation(result.gitProject.rootDetected, "git project root detection failed");
		assertValidation(!result.gitProject.idIsGlobal, "git project incorrectly fell back to global");
		assertValidation(result.nonGitFallback.idIsGlobal, "non-git directory did not fall back to global");
		assertValidation(result.override.rootMatchesOverride, "PI_PROJECT_DIR override did not set project root");
		assertValidation(result.globalFallbackInstincts.count === 2, "global fallback instinct count mismatch");
		assertValidation(result.globalFallbackInstincts.allGlobal, "global fallback instincts were not labeled global");
		assertValidation(result.instinctRouting.globalDirMatches, "global instinct routing mismatch");
		assertValidation(result.instinctRouting.projectDirMatches, "project instinct routing mismatch");

		return result;
	} finally {
		if (previousAgentDir === undefined) {
			delete process.env.PI_CODING_AGENT_DIR;
		} else {
			process.env.PI_CODING_AGENT_DIR = previousAgentDir;
		}
		if (previousProjectDir === undefined) {
			delete process.env.PI_PROJECT_DIR;
		} else {
			process.env.PI_PROJECT_DIR = previousProjectDir;
		}
		if (previousClaudeProjectDir === undefined) {
			delete process.env.CLAUDE_PROJECT_DIR;
		} else {
			process.env.CLAUDE_PROJECT_DIR = previousClaudeProjectDir;
		}
		await rm(tempRoot, { recursive: true, force: true });
	}
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	void runScopeValidation()
		.then((result) => {
			console.log(JSON.stringify(result, null, 2));
		})
		.catch((error) => {
			console.error(error instanceof Error ? error.message : String(error));
			process.exitCode = 1;
		});
}
